# TODO: Update page with accurate info
# List order: hp, atk, def, spc, spe
Pidgeot:
  type: [Normal, Flying]
  level: 66
  stats: [214, 140, 150, 137, 152]
  moves: ["Mirror Move", "Rest", "Fly", "Double-Edge"]
Kabutops:
  type: [Rock, Water]
  level: 68
  stats: [188, 203, 177, 143, 145]
  moves: ["Substitute", "Rest", "Surf", "Slash"]
Drowzee:
  type: Psychic
  level: 81
  stats: [212, 120, 107, 165, 98]
  moves: ["Body Slam", "Hypnosis", "Rest", "Psychic"]
Muk:
  type: Poison
  level: 73
  stats: [243, 167, 130, 145, 118]
  moves: ["Acid Armor", "Explosion", "Rest", "Body Slam"]
Exeggutor:
  type: [Grass, Psychic]
  level: 53
  stats: [195, 138, 124, 162, 83]
  moves: ["Stun Spore", "Mega Drain", "Explosion", "Psychic"]
Sandshrew:
  type: Ground
  level: 80
  stats: [215, 158, 193, 95, 122]
  moves: ["Earthquake", "Rock Slide", "Substitute", "Swords Dance"]
Fearow:
  type: [Normal, Flying]
  level: 67
  stats: [188, 153, 136, 132, 147]
  moves: ["Drill Peck", "Agility", "Substitute", "Double-Edge"]
Raticate:
  type: Normal
  level: 68
  stats: [166, 153, 113, 109, 164]
  moves: ["Hyper Beam", "Focus Energy", "Blizzard", "Hyper Fang"]
Gengar:
  type: [Ghost, Poison]
  level: 55
  stats: [156, 112, 93, 173, 153]
  moves: ["Night Shade", "Substitute", "Thunderbolt", "Explosion"] 
Hitmonlee:
  type: Fighting
  level: 68
  stats: [174, 183, 117, 94, 155]
  moves: ["Focus Energy", "Substitute", "Mega Kick", "Hi Jump Kick"]
Vaporeon:
  type: Water
  level: 57
  stats: [251, 80, 104, 153, 104]
  moves: ["Blizzard", "Rest", "Acid Armor", "Surf"]
Haunter:
  type: [Ghost, Poison]
  level: 60
  stats: [163, 66, 96, 170, 150]
  moves: ["Psychic", "Hypnosis", "Night Shade", "Thunderbolt"]
Tangela:
  type: Grass
  level: 65
  stats: [193, 107, 181, 179, 118]
  moves: ["Stun Spore", "Growth", "Mega Drain", "Body Slam"]
Victreebel:
  type: [Grass, Poison]
  level: 57
  stats: [194, 150, 103, 148, 112]
  moves: ["Razor Leaf", "Swords Dance", "Sleep Powder", "Body Slam"]
Chansey:
  type: Normal
  level: 53
  stats: [362, 17, 38, 138, 83]
  moves: ["Seismic Toss", "Thunder Wave", "Reflect", "Softboiled"]
Nidoking:
  type: [Poison, Ground]
  level: 63
  stats: [207, 149, 133, 136, 144]
  moves: ["Thunderbolt", "Earthquake", "Blizzard", "Focus Energy"]
Psyduck:
  type: Water
  level: 87
  stats: [225, 116, 125, 144, 136]
  moves: ["Rest", "Surf", "Blizzard", "Body Slam"]
Dodrio:
  type: [Normal, Flying]
  level: 53
  stats: [166, 177, 96, 100, 167]
  moves: ["Substitute", "Hyper Beam", "Double-Edge", "Fly"]
Wigglytuff:
  type: Normal
  level: 60
  stats: [257, 129, 91, 92, 80]
  moves: ["Sing", "Double-Edge", "Blizzard", "Rest"]
Weezing:
  type: Poison
  level: 63
  stats: [195, 150, 175, 154, 83]
  moves: ["Explosion", "Thunderbolt", "Sludge", "Substitute"]
Cloyster:
  type: [Water, Ice]
  level: 58
  stats: [155, 143, 254, 141, 121]
  moves: ["Blizzard", "Explosion", "Rest", "Surf"]
Gyarados:
  type: [Water, Flying]
  level: 58
  stats: [207, 173, 127, 158, 129]
  moves: ["Rest", "Blizzard", "Body Slam", "Hydro Pump"]
Zapdos:
  type: [Electric, Flying]
  level: 54
  stats: [186, 134, 124, 169, 137]
  moves: ["Substitute", "Drill Peck", "Thunderbolt", "Thunder Wave"]
Arcanine:
  type: Fire
  level: 70
  stats: [227, 191, 139, 147, 143]
  moves: ["Body Slam", "Rest", "Fire Blast", "Dig"]
Machamp:
  type: Fighting
  level: 71
  stats: [226, 191, 154, 131, 111]
  moves: ["Low Kick", "Strength", "Rest", "Earthquake"]
Onix:
  type: [Rock, Ground]
  level: 80
  stats: [179, 118, 264, 161, 109]
  moves: ["Bind", "Earthquake", "Explosion", "Body Slam"]
Clefable:
  type: Normal
  level: 68
  stats: [237, 117, 118, 154, 115]
  moves: ["Rest", "Body Slam", "Psychic", "Blizzard"]
Rapidash:
  type: Fire
  level: 73
  stats: [183, 162, 108, 156, 193]
  moves: ["Fire Spin", "Hyper Beam", "Body Slam", "Fire Blast"]
Alakazam:
  type: Psychic
  level: 53
  stats: [129, 78, 61, 161, 164]
  moves: ["Ice Punch", "Flash", "Substitute", "Psychic"]
Tauros:
  type: Normal
  level: 55
  stats: [175, 150, 139, 109, 150]
  moves: ["Blizzard", "Body Slam", "Earthquake", "Hyper Beam"]
Poliwhirl:
  type: Water
  level: 70
  stats: [207, 143, 125, 168, 119]
  moves: ["Psychic", "Surf", "Hypnosis", "Amnesia"]
Venonat:
  type: [Bug, Poison]
  level: 90
  stats: [230, 139, 122, 129, 118]
  moves: ["Psychic", "Stun Spore", "Rest", "Double-Edge"]
Pikachu:
  type: Electric
  level: 83
  stats: [189, 101, 103, 129, 189]
  moves: ["Thunderbolt", "Seismic Toss", "Thunder Wave", "Substitute"]
Starmie:
  type: [Water, Psychic]
  level: 55
  stats: [159, 100, 123, 143, 154]
  moves: ["Thunderbolt", "Psychic", "Substitute", "Thunder Wave"]
Venusaur:
  type: [Grass, Poison]
  level: 59
  stats: [191, 131, 132, 160, 120]
  moves: ["Body Slam", "Razor Leaf", "Swords Dance", "Sleep Powder"]
Jolteon:
  type: Electric
  level: 55
  stats: [146, 106, 104, 164, 183]
  moves: ["Thunderbolt", "Thunder Wave", "Pin Missile", "Substitute"]
Rhydon:
  type: [Rock, Ground]
  level: 55
  stats: [217, 175, 171, 87, 70]
  moves: ["Rock Slide", "Rest", "Substitute", "Earthquake"]
Electrode:
  type: Electric
  level: 61
  stats: [160, 95, 115, 144, 191]
  moves: ["Light Screen", "Thunderbolt", "Explosion", "Thunder Wave"]
Parasect:
  type: [Bug, Grass]
  level: 75
  stats: [221, 191, 146, 151, 86]
  moves: ["Body Slam", "Swords Dance", "Mega Drain", "Spore"]
Blastoise:
  type: Water
  level: 60
  stats: [201, 144, 150, 117, 144]
  moves: ["Earthquake", "Reflect", "Hydro Pump", "Rest"]
Articuno:
  type: [Ice, Flying]
  level: 55
  stats: [195, 112, 139, 174, 133]
  moves: ["Double-Edge", "Rest", "Agility", "Blizzard"]
Snorlax:
  type: Normal
  level: 55
  stats: [258, 147, 93, 114, 47]
  moves: ["Ice Beam", "Amnesia", "Rest", "Body Slam"]
Slowbro:
  type: [Water, Psychic]
  level: 53
  stats: [192, 108, 150, 126, 71]
  moves: ["Psychic", "Amnesia", "Rest", "Surf"]
Persian:
  type: Normal
  level: 57
  stats: [169, 119, 108, 105, 172]
  moves: ["Slash", "Substitute", "Bubblebeam", "Thunderbolt"]
Kingler:
  type: Water
  level: 60
  stats: [161, 194, 179, 99, 131]
  moves: ["Crabhammer", "Body Slam", "Substitute", "Swords Dance"]
Ditto:
  type: Normal
  level: 100
  stats: [256, 113, 127, 119, 169]
  moves: ["Transform"]
Lapras:
  type: [Water, Ice]
  level: 58
  stats: [219, 108, 115, 109, 146]
  moves: ["Surf", "Rest", "Blizzard", "Thunderbolt"]
Nidoqueen:
  type: [Poison, Ground]
  level: 63
  stats: [230, 144, 146, 131, 122]
  moves: ["Blizzard", "Reflect", "Earthquake", "Rest"]
Kadabra:
  type: Psychic
  level: 60
  stats: [149, 63, 68, 178, 168]
  moves: ["Substitute", "Psychic", "Thunder Wave", "Seismic Toss"]
