exists: true
name: Amnesia
boosts:
  spa: 2
  spd: 2
num: 133
accuracy: true
basePower: 0
category: Status
pp: 20
priority: 0
flags:
  snatch: 1
secondary: null
target: self
type: Psychic
zMove:
  effect: clearnegativeboost
contestType: Cute
desc: Raises the user's Special by 2 stages.
shortDesc: Raises the user's Special by 2.
id: amnesia
fullname: 'move: Amnesia'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Psychic
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
