exists: true
name: Blizzard
accuracy: 90
target: normal
basePower: 120
num: 59
category: Special
pp: 5
priority: 0
flags:
  protect: 1
  mirror: 1
  wind: 1
secondary: &ref_0
  chance: 10
  status: frz
type: Ice
contestType: Beautiful
desc: Has a 10% chance to freeze the target.
shortDesc: 10% chance to freeze the target.
id: blizzard
fullname: 'move: Blizzard'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Ice
secondaries:
  - *ref_0
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 140
zMove:
  basePower: 190
