exists: false
name: c
id: c
fullname: 'move: c'
effectType: Move
num: 0
gen: 0
shortDesc: ''
desc: ''
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
type: ''
basePower: .nan
critRatio: 1
baseMoveType: ''
secondary: null
secondaries: null
hasSheerForce: false
priority: 0
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
pp: .nan
noPPBoosts: false
isZ: false
isMax: false
flags: {}
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 100
zMove:
  basePower: 100
