exists: true
name: Drill Peck
num: 65
accuracy: 100
basePower: 80
category: Physical
pp: 20
priority: 0
flags:
  contact: 1
  protect: 1
  mirror: 1
  distance: 1
secondary: null
target: any
type: Flying
contestType: Cool
desc: No additional effect.
shortDesc: No additional effect.
id: drillpeck
fullname: 'move: Drill Peck'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Flying
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 130
zMove:
  basePower: 160
