exists: true
name: Earthquake
num: 89
accuracy: 100
basePower: 100
category: Physical
pp: 10
priority: 0
flags:
  protect: 1
  mirror: 1
  nonsky: 1
secondary: null
target: allAdjacent
type: Ground
contestType: Tough
desc: No additional effect.
shortDesc: No additional effect.
id: earthquake
fullname: 'move: Earthquake'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Ground
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 130
zMove:
  basePower: 180
