exists: true
name: Fire Blast
secondary: &ref_0
  chance: 30
  status: brn
basePower: 120
num: 126
accuracy: 85
category: Special
pp: 5
priority: 0
flags:
  protect: 1
  mirror: 1
target: normal
type: Fire
contestType: Beautiful
desc: Has a 30% chance to burn the target.
shortDesc: 30% chance to burn the target.
id: fireblast
fullname: 'move: Fire Blast'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Fire
secondaries:
  - *ref_0
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 140
zMove:
  basePower: 190
