exists: true
name: Focus Energy
condition: {}
num: 116
accuracy: true
basePower: 0
category: Status
pp: 30
priority: 0
flags:
  snatch: 1
volatileStatus: focusenergy
secondary: null
target: self
type: Normal
zMove:
  boost:
    accuracy: 1
contestType: Cool
desc: >-
  While the user remains active, its chance for a critical hit is quartered.
  Fails if the user already has the effect. If any Pokemon uses Haze, this
  effect ends.
shortDesc: Quarters the user's chance for a critical hit.
id: focusenergy
fullname: 'move: Focus Energy'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Normal
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
