exists: true
name: Growth
boosts:
  spa: 1
  spd: 1
pp: 40
num: 74
accuracy: true
basePower: 0
category: Status
priority: 0
flags:
  snatch: 1
secondary: null
target: self
type: Normal
zMove:
  boost:
    spa: 1
contestType: Beautiful
desc: Raises the user's Special by 1 stage.
shortDesc: Raises the user's Special by 1.
id: growth
fullname: 'move: Growth'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Normal
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
