exists: true
name: Hypnosis
accuracy: 60
num: 95
basePower: 0
category: Status
pp: 20
priority: 0
flags:
  protect: 1
  reflectable: 1
  mirror: 1
status: slp
secondary: null
target: normal
type: Psychic
zMove:
  boost:
    spe: 1
contestType: Clever
desc: Causes the target to fall asleep.
shortDesc: Causes the target to fall asleep.
id: hypnosis
fullname: 'move: Hypnosis'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Psychic
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
