exists: true
name: Ice Beam
basePower: 95
num: 58
accuracy: 100
category: Special
pp: 10
priority: 0
flags:
  protect: 1
  mirror: 1
secondary: &ref_0
  chance: 10
  status: frz
target: normal
type: Ice
contestType: Beautiful
desc: Has a 10% chance to freeze the target.
shortDesc: 10% chance to freeze the target.
id: icebeam
fullname: 'move: Ice Beam'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Ice
secondaries:
  - *ref_0
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 130
zMove:
  basePower: 175
