exists: true
name: Light Screen
num: 113
accuracy: true
basePower: 0
category: Status
pp: 30
priority: 0
flags: {}
volatileStatus: lightscreen
condition: {}
target: self
type: Psychic
desc: >-
  While the user remains active, its Special is doubled when taking damage.
  Critical hits ignore this effect. If any Pokemon uses Haze, this effect ends.
shortDesc: While active, user's Special is 2x when damaged.
id: lightscreen
fullname: 'move: Light Screen'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Psychic
secondary: null
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
