exists: true
name: Mega Drain
pp: 10
flags:
  protect: 1
  mirror: 1
num: 72
accuracy: 100
basePower: 40
category: Special
priority: 0
drain:
  - 1
  - 2
secondary: null
target: normal
type: Grass
zMove:
  basePower: 120
contestType: Clever
desc: The user recovers 1/2 the HP lost by the target, rounded down.
shortDesc: User recovers 50% of the damage dealt.
id: megadrain
fullname: 'move: Mega Drain'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Grass
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 90
