exists: true
name: Mega Kick
num: 25
accuracy: 75
basePower: 120
category: Physical
pp: 5
priority: 0
flags:
  contact: 1
  protect: 1
  mirror: 1
secondary: null
target: normal
type: Normal
contestType: Cool
desc: No additional effect.
shortDesc: No additional effect.
id: megakick
fullname: 'move: Mega Kick'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Normal
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 140
zMove:
  basePower: 190
