exists: true
name: Psychic
secondary: &ref_0
  chance: 33
  boosts:
    spa: -1
    spd: -1
num: 94
accuracy: 100
basePower: 90
category: Special
pp: 10
priority: 0
flags:
  protect: 1
  mirror: 1
target: normal
type: Psychic
contestType: Clever
desc: Has a 33% chance to lower the target's Special by 1 stage.
shortDesc: 33% chance to lower the target's Special by 1.
id: psychic
fullname: 'move: Psychic'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Psychic
secondaries:
  - *ref_0
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 130
zMove:
  basePower: 175
