exists: true
name: Seismic Toss
ignoreImmunity: true
basePower: 1
num: 69
accuracy: 100
damage: level
category: Physical
pp: 20
priority: 0
flags:
  contact: 1
  protect: 1
  mirror: 1
  nonsky: 1
secondary: null
target: normal
type: Fighting
maxMove:
  basePower: 75
contestType: Tough
desc: >-
  Deals damage to the target equal to the user's level. This move ignores type
  immunity.
shortDesc: Damage = user's level. Can hit Ghost types.
id: seismictoss
fullname: 'move: Seismic Toss'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Fighting
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
zMove:
  basePower: 100
