exists: true
name: Sing
flags:
  protect: 1
  reflectable: 1
  mirror: 1
  sound: 1
num: 47
accuracy: 55
basePower: 0
category: Status
pp: 15
priority: 0
status: slp
secondary: null
target: normal
type: Normal
zMove:
  boost:
    spe: 1
contestType: Cute
desc: Causes the target to fall asleep.
shortDesc: Causes the target to fall asleep.
id: sing
fullname: 'move: Sing'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Normal
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
