exists: true
name: Slash
critRatio: 2
num: 163
accuracy: 100
basePower: 70
category: Physical
pp: 20
priority: 0
flags:
  contact: 1
  protect: 1
  mirror: 1
  slicing: 1
secondary: null
target: normal
type: Normal
contestType: Cool
desc: Has a higher chance for a critical hit.
shortDesc: High critical hit ratio.
id: slash
fullname: 'move: Slash'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
baseMoveType: Normal
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
maxMove:
  basePower: 120
zMove:
  basePower: 140
