exists: true
name: Spore
num: 147
accuracy: 100
basePower: 0
category: Status
pp: 15
priority: 0
flags:
  powder: 1
  protect: 1
  reflectable: 1
  mirror: 1
status: slp
secondary: null
target: normal
type: Grass
zMove:
  effect: clearnegativeboost
contestType: Beautiful
desc: Causes the target to fall asleep.
shortDesc: Causes the target to fall asleep.
id: spore
fullname: 'move: Spore'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Grass
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
