exists: true
name: Substitute
num: 164
accuracy: true
basePower: 0
category: Status
pp: 10
priority: 0
volatileStatus: substitute
condition:
  onTryHitPriority: -1
secondary: null
target: self
type: Normal
flags: {}
desc: >-
  The user takes 1/4 of its maximum HP, rounded down, and puts it into a
  substitute to take its place in battle. The substitute has 1 HP plus the HP
  used to create it, and is removed once enough damage is inflicted on it or 255
  damage is inflicted at once, or if the user switches out or faints. Until the
  substitute is broken, it receives damage from all attacks made by the opposing
  Pokemon and shields the user from status effects and stat stage changes caused
  by the opponent, unless the effect is Disable, Leech Seed, sleep, primary
  paralysis, or secondary confusion and the user's substitute did not break. The
  user still takes normal damage from status effects while behind its
  substitute, unless the effect is confusion damage, which is applied to the
  opposing Pokemon's substitute instead. If the substitute breaks during a
  multi-hit attack, the attack ends. Fails if the user does not have enough HP
  remaining to create a substitute, or if it already has a substitute. The user
  will create a substitute and then faint if its current HP is exactly 1/4 of
  its maximum HP.
shortDesc: User takes 1/4 its max HP to put in a Substitute.
id: substitute
fullname: 'move: Substitute'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Normal
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
ignoreImmunity: true
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
