exists: true
name: Thunder Wave
accuracy: 100
num: 86
basePower: 0
category: Status
pp: 20
priority: 0
flags:
  protect: 1
  reflectable: 1
  mirror: 1
status: par
ignoreImmunity: false
secondary: null
target: normal
type: Electric
zMove:
  boost:
    spd: 1
contestType: Cool
desc: Paralyzes the target. This move does not ignore type immunity.
shortDesc: Paralyzes the target.
id: thunderwave
fullname: 'move: Thunder Wave'
effectType: Move
gen: 1
isNonstandard: null
noCopy: false
affectsFainted: false
sourceEffect: ''
critRatio: 1
baseMoveType: Electric
secondaries: null
hasSheerForce: false
ignoreNegativeOffensive: false
ignorePositiveDefensive: false
ignoreOffensive: false
ignoreDefensive: false
noPPBoosts: false
isZ: false
isMax: false
pressureTarget: ''
nonGhostTarget: ''
ignoreAbility: false
spreadHit: false
forceSTAB: false
noSketch: false
